# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8efe61236fc771be0ad631e40c242da0c939ceb7ce4412f6e0aed146785861af82f7a38e35a61027c623ce5bad0a66eeb0de59bafb9464e393753161ab8b0d1

test:
  secret_key_base: 445895d99549f6a50b1d7d8868da0322a0ac56a381dfe959c84adda6766a7deccf5a4057a8b5ddc8951b9b9e04e29710e241669d0da55263837f08a6f97b757e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
